package com.example.onlineshop.model

import com.squareup.moshi.Json

data class OrderResponse(
//    val _links: LinksX,
//    val billing: BillingX,
//    val cart_hash: String,
//    val cart_tax: String,
//    val coupon_lines: List<Any>,
//    val created_via: String,
//    val currency: String,
//    val customer_id: Int,
//    val customer_ip_address: String,
//    val customer_note: String,
//    val customer_user_agent: String,
//    val date_completed: Any,
//    val date_completed_gmt: Any,
//    val date_created: String,
//    val date_created_gmt: String,
//    val date_modified: String,
//    val date_modified_gmt: String,
//    val date_paid: String,
//    val date_paid_gmt: String,
//    val discount_tax: String,
//    val discount_total: String,
//    val fee_lines: List<Any>,
    @Json(name = "id")val id: Int,
    @Json(name = "line_items")val line_items: List<LineItem>,
//    val meta_data: List<MetaDataX>,
//    val number: String,
//    val order_key: String,
//    val parent_id: Int,
//    val payment_method: String,
//    val payment_method_title: String,
//    val prices_include_tax: Boolean,
//    val refunds: List<Any>,
//    val shipping: ShippingX,
//    val shipping_lines: List<ShippingLine>,
//    val shipping_tax: String,
//    val shipping_total: String,
//    val status: String,
//    val tax_lines: List<TaxLine>,
//    @Json(name = "total") val total: String,
//    val total_tax: String,
//    val transaction_id: String,
//    val version: String
)